### ISSUE TITLE
Integrity db error between geoapps tables on upgrade from 3.x to 4.x

### ISSUE THREAD

**Issue by marthamareal** [GeoNode/geonode-mapstore-client#905]
## Expected Behavior
- User should be able to perform all actions on available data after upgrading from 3.x to 4.x

## Actual Behavior
- An integrity error is raised when a user tries to delete a geoapp/dashbord which was created with 3.x after upgrading to 4.x.
- With dashboards, in 3.3.x, we assign polymorphic_ctype = dashboard hence on retrieving it after an upgrade, the error 'NoneType' object has no attribute 'objects' is raised.

## Steps to Reproduce the Problem

  1. Start a geonode-project with 3.x
  2. Create resources eg layers, maps, geostories, and dashboards
  3. Upgrade project to 4.x
  4. Delete a geostory/geoapp created with 3.x
  5. An integrity error will be raised.
